// GENERATED by scripts/extract-work-details.mjs — do not edit by hand.
// Source: ../../../Nexkeys Website/work.html
// The long-form project write-ups, preserved verbatim (plan N1).
// Re-run the script if the source copy is revised.

import type { WorkDetail } from '@/lib/types';

export const WORK_DETAILS: WorkDetail[] = [
  {
    "id": "arobix",
    "index": "01",
    "name": "Arobix Business Website",
    "tags": [
      "Web Development",
      "UI/UX Design",
      "Branding"
    ],
    "paragraphs": [
      "A modern finance business webpage built to showcase a clean, elegant digital presence. Our redesign elevated the brand identity through a minimal layout, high-contrast typography, and sharp user-focused content sections. Lightweight, fully responsive, and SEO-optimised for both desktop and mobile users.",
      "We implemented a modular sectioning approach allowing the business to scale or adjust offerings without major structural changes. On-page SEO, improved accessibility, and performance enhancements deliver a smooth browsing experience that builds visitor trust."
    ],
    "url": "https://arobix.netlify.app/",
    "label": "AR"
  },
  {
    "id": "currencyx",
    "index": "02",
    "name": "Currency Exchange Calculator",
    "tags": [
      "Web App",
      "Fintech",
      "UI Design"
    ],
    "paragraphs": [
      "CurrencyExchange101 is a lightweight, real-time currency calculator designed for quick, accurate conversions across common global currencies. A structured layout with a simplified UI reduces cognitive load and conversions done instantly, no complexity.",
      "Live exchange rate logic ensures accuracy without sacrificing speed. Smooth animations, mobile responsiveness, and a visually balanced UI make Exchange101 a clean and dependable micro-utility."
    ],
    "url": "https://currencyexchange101.netlify.app/",
    "label": "FX"
  },
  {
    "id": "edulearn",
    "index": "03",
    "name": "EduLearning Course Platform",
    "tags": [
      "Learning Platform",
      "UI/UX Design",
      "Responsive Design"
    ],
    "paragraphs": [
      "A next-generation education interface focused on improving accessibility for learners of all ages. Clear sections, structured lessons, and a friendly layout paired with a mobile-first methodology ensuring learners on any device can easily consume content.",
      "Load times were minimised, typography fine-tuned for readability, and the architecture structured so educators can adapt or expand modules as needed. A showcase of educational UI, information architecture, and responsive design working in harmony."
    ],
    "url": "https://edulearningfreeplatform.netlify.app/",
    "label": "EL"
  },
  {
    "id": "kinkart",
    "index": "04",
    "name": "Kinkart Mini E-Commerce",
    "tags": [
      "E-Commerce",
      "Web Development",
      "UI/UX"
    ],
    "paragraphs": [
      "A beautifully crafted mini e-commerce storefront that mirrors the look and feel of a modern online shop. Clean product cards, compelling CTAs, hero banners, and a polished layout that keeps products at the centre of attention.",
      "Sharp spacing, typography balance, and grid alignment ensure a premium browsing experience. Fully responsive breakpoints deliver consistency across all device sizes, a demonstration of how e-commerce UI blends simplicity with brand-forward aesthetics."
    ],
    "url": "https://kinkart.netlify.app/",
    "label": "KK"
  },
  {
    "id": "valor-perks",
    "index": "05",
    "name": "Valor Perks — Token Earning Platform",
    "tags": [
      "Fintech",
      "Web App",
      "UI/UX Design"
    ],
    "paragraphs": [
      "Valor Perks is a high-velocity token trading interface built for traders who demand speed, precision and trust in one place. The platform supports real-time token pair swaps starting with VPT/NGN, ETH/BTC with live market rates, a built-in token earning and trading system, multi-chain support and an ultra-low fee structure that positions it competitively against centralised exchanges.",
      "We engineered the UI around minimal friction: from the trading widget with percentage helpers (25%/50%/Max) to the live market ticker and latest Token news feed, every element serves a trader's workflow. A 4-step onboarding flow — SIGNUP/LOGIN, PURCHASE TOKEN, START TRADING. A landmark demonstration of fintech UI craft at Awwwards quality."
    ],
    "url": "https://valor-perks.web.app/",
    "label": "SN"
  },
  {
    "id": "gamevault",
    "index": "06",
    "name": "GameVault — Secure Game Account Escrow ⚡ Live",
    "tags": [
      "⚡ Live",
      "Fintech",
      "Escrow Platform",
      "Backend Integration",
      "Web Development"
    ],
    "paragraphs": [
      "GameVault is a fully operational escrow service that eliminates fraud in game account trading across Nigeria. Buyers send payment to GameVault — funds are held securely and released to the seller only after the buyer confirms successful account delivery. No scams. No risk. Just trust.",
      "The platform integrates a Google Forms-powered trade backend with Paystack payment support, bank transfer compatibility for GTBank, Opay, and Moniepoint, and WhatsApp-based support resolution. Real-time trust indicators, animated scroll reveals, and a clear 5-step escrow flow give both parties the confidence to transact. This is a live, production-grade platform actively processing real trades in the Nigerian gaming market."
    ],
    "url": "https://gameplugvault.netlify.app/",
    "label": "GV"
  },
  {
    "id": "zapcash",
    "index": "07",
    "name": "ZapCash Lite — Micro-Earning Platform",
    "tags": [
      "Fintech",
      "Web App",
      "UI/UX Design"
    ],
    "paragraphs": [
      "ZapCash Lite is a micro-task earning platform purpose-built for the Nigerian market — allowing users to convert everyday online activity into real naira paid directly to their bank account or as airtime. The 14-task library includes Instagram follows, video watches, Telegram group joins, friend referrals, WhatsApp channel subscriptions, and app downloads, each awarding 1–3 points toward a ₦500 minimum cashout.",
      "We focused the design around trust and motivation: zero credit card required, 60-second signup, a live leaderboard, and an earnings dashboard built for clarity on any Android smartphone. The result is a platform that is simultaneously simple enough for first-time earners and credible enough to retain an active base of 100+ daily users across Nigeria's 36 states."
    ],
    "url": "https://zapcash-lite.netlify.app/",
    "label": "ZC"
  },
  {
    "id": "gombay",
    "index": "08",
    "name": "Gombay — Premium Gaming Hub",
    "tags": [
      "Gaming",
      "UI/UX Design",
      "Web Development"
    ],
    "paragraphs": [
      "Gombay is a cinematic gaming hub built under the \"Void Citadel\" aesthetic — near-black void backgrounds, electric violet primary accents, neon cyan for live states, gold for premium tiers, and Orbitron display typography that commands respect from the first scroll. The platform hosts 14 game titles including GTA V, Spider-Man, Call of Duty, FIFA, PES, and Mortal Kombat vs DC.",
      "It features a 3-slide auto-rotating hero carousel with HUD-style overlays, scanline animations, and parallax art panels; a genre-filtered 12-card editorial game grid with a 2-row featured card; an online friends panel with avatar status indicators; a top charts list; and a new releases carousel with drag-scroll. Every action — wishlisting, downloading, friend invites — triggers a custom toast notification. A landmark showcase of gaming-grade UI precision."
    ],
    "url": "https://gombay.netlify.app/",
    "label": "GB"
  },
  {
    "id": "goodfood",
    "index": "09",
    "name": "GoodFood — Restaurant & Delivery Platform",
    "tags": [
      "Restaurant",
      "Editorial Web Design",
      "E-Commerce"
    ],
    "paragraphs": [
      "GoodFood is a luxury food-magazine-grade restaurant platform built under the \"Warm Harvest Editorial\" aesthetic — cream and espresso base tones, terracotta clay accents, sage green secondaries, and Cormorant Garamond serif typography that elevates the dining experience before a single order is placed.",
      "The platform features a drag-to-scroll 8-category carousel, a menu section with live filter pills and staggered reveal animations, an editorial About section with animated counters, a 4-card reviews grid, and a fully functional cart system with quantity management, live subtotals, and a checkout flow. Subtle hero parallax, debounced live search with dropdown results, and a scroll-reveal system driven by IntersectionObserver cement GoodFood as a benchmark for hospitality web design."
    ],
    "url": "https://goodfoodsite.netlify.app/",
    "label": "GF"
  },
  {
    "id": "nitec",
    "index": "10",
    "name": "Nitec — Underground Brand Storefront",
    "tags": [
      "E-Commerce",
      "Web Development",
      "UI/UX Design"
    ],
    "paragraphs": [
      "Nitec is a fully functional e-commerce storefront for curated underground brands — stocking 24 products across electronics, clothing, art prints, accessories, books, and home goods. The ultra-dark editorial aesthetic positions Nitec as a premium discovery destination for products you won't find on mainstream platforms like Jumia or Amazon.",
      "We built a complete shopping experience: live category filtering across 6 departments, price-range filters (under $25/$50/$100), multi-mode sorting (A–Z, newest, price), a real-time cart with quantity management, badge systems for Best Seller and New Drop items, hover animations on product cards, and a seamless grid layout. Fully responsive across mobile, tablet, and desktop — a complete front-end e-commerce build with production-grade attention to detail."
    ],
    "url": "https://nitec-ecommerce.netlify.app/",
    "label": "NT"
  },
  {
    "id": "stakex",
    "index": "11",
    "name": "StakeX — Sports Betting Dashboard",
    "tags": [
      "Gaming",
      "Dashboard UI",
      "Web Design"
    ],
    "paragraphs": [
      "StakeX is an immersive sports betting dashboard built under the \"Ember Underground\" aesthetic — obsidian-black base, amber-gold primary, electric lime for live odds, and Barlow Condensed display typography that rivals the production quality of platforms like Bet9ja and Betway.",
      "Key features include a live odds ticker flashing every 5 seconds, a 2-column hero with a featured match panel and promotional bonus stack, a 3×2 match grid with real-time clock, a 6-column games grid, a live leaderboard, and a recent bets panel. The platform includes a built-in balance system, a toast notification engine, IntersectionObserver scroll reveals, and a full mobile sidebar overlay — a comprehensive showcase of data-dense, high-stakes dashboard design."
    ],
    "url": "https://stakexcasino.netlify.app/",
    "label": "SX"
  },
  {
    "id": "nexplay",
    "index": "12",
    "name": "NexPlay — Real-Time 1v1 Gaming Arena ⚡ Live",
    "tags": [
      "⚡ Live",
      "Live Gaming Platform",
      "Real-Time Web App",
      "Multiplayer"
    ],
    "paragraphs": [
      "NexPlay is a fully live production multiplayer platform where 1,500+ active players compete daily in skill-based 1v1 duels — no accounts required, no cryptocurrency, zero setup friction. Create a room, share a code, start playing in under 10 seconds.",
      "Seven distinct game modes power the platform: Tic-Tac-Toe, Rock-Paper-Scissors, Connect Four, Memory Card Flip, Trivia Duel, Word Race, and Quick Math Duel — each with its own competitive logic, pacing, and win conditions. Real-time room management, instant peer matchmaking, and a zero-barrier anonymous-play system make NexPlay the definitive proof that genuinely functional, polished web gaming products can be built and deployed at speed."
    ],
    "url": "https://nexplays.netlify.app/",
    "label": "NP"
  },
  {
    "id": "jenny-wines",
    "index": "13",
    "name": "Jenny Wines — Premium Wine Store ⚡ Live",
    "tags": [
      "⚡ Live",
      "E-Commerce",
      "Live Business",
      "Web Design",
      "Branding"
    ],
    "paragraphs": [
      "Jenny Wines is a fully operational premium wine retail business serving customers across Nigeria. The website is the brand's primary sales and discovery platform — housing curated selections including Giacobazzi, Rubis, Ocean Beach, and Baileys, all original, hand-verified before dispatch, and available for swift nationwide delivery with safe, elegant packaging.",
      "We built the site to embody premium positioning: a cinematic video hero, rich product imagery, a curated product showcase, customer testimonials, and a clear delivery and contact pipeline tailored for Nigerian buyers. With over 1,000 satisfied customers and a growing delivery footprint from Lagos to Port Harcourt and Abuja, Jenny Wines is a live e-commerce success story — demonstrating how great web design translates directly into measurable business growth."
    ],
    "url": "https://jennywines.netlify.app/",
    "label": "JW"
  },
  {
    "id": "vrkids",
    "index": "14",
    "name": "VRKids — Educational VR Platform",
    "tags": [
      "EdTech",
      "VR / AR",
      "UI/UX Design",
      "Responsive Web"
    ],
    "paragraphs": [
      "VRKids is an educational technology platform designed to bring Virtual and Augmented Reality learning to children at an early age — making curriculum content experiential, immersive, and genuinely engaging. The platform showcases VR game products, a downloadable AR guide, and an interactive storefront built for parents, schools, and EdTech procurement teams.",
      "The design carefully balances the warmth and approachability required for a children's education product with the credibility and structure needed to earn institutional trust. A mobile-first build ensures the platform performs flawlessly on classroom tablets, parent smartphones, and administrator desktops alike. VRKids is a compelling demonstration of how emerging technology products can be presented with clarity, commercial confidence, and genuine creative craft."
    ],
    "url": "https://vr-kids.netlify.app/",
    "label": "VR"
  },
  {
    "id": "sellapage",
    "index": "15",
    "name": "Sellapage — SaaS Storefront Platform Live",
    "tags": [
      "Live",
      "SaaS Platform",
      "E-Commerce",
      "Web Development"
    ],
    "paragraphs": [
      "Sellapage is a startup SaaS platform built by NexKeys Agency that empowers entrepreneurs and small businesses to build product-based pages, manage digital storefronts, and unlock upgrade-based business features — all without needing any technical knowledge. The platform bridges the gap between a simple link-in-bio tool and a full e-commerce solution, giving sellers in emerging markets a powerful yet accessible launchpad.",
      "We engineered the entire product from architecture to UI — a clean dashboard for managing products and orders, a public-facing storefront builder, and a tiered upgrade system that unlocks premium capabilities as a business grows. The result is a live, production-grade SaaS product actively serving real sellers across Nigeria."
    ],
    "url": "https://sellapage.com.ng/",
    "label": "SP"
  },
  {
    "id": "gameplug-hq",
    "index": "16",
    "name": "Game Plug HQ — Tournament Organizer",
    "tags": [
      "Gaming",
      "Tournament Platform",
      "Web App"
    ],
    "paragraphs": [
      "Game Plug HQ is a fully featured online gaming tournament organising platform built around the Nigerian eFootball competitive scene. The platform includes an admin panel for tournament management, a player portal for registration and match tracking, an active/live dashboard displaying real-time bracket progression, and all the core infrastructure a tournament platform demands — fixtures, standings, player profiles, and result submissions.",
      "We designed the product around two distinct user roles — organiser and participant — each with a tailored interface that simplifies what are otherwise complex tournament logistics. The live dashboard delivers real-time match updates without page reloads, keeping spectators and players engaged throughout the competition. A definitive showcase of web app architecture meeting gaming culture."
    ],
    "url": "https://gameplug-efootball-tournament.netlify.app/",
    "label": "GP"
  }
];

export const WORK_DETAIL_BY_ID = Object.fromEntries(
  WORK_DETAILS.map((d) => [d.id, d])
) as Record<string, WorkDetail>;
