// GENERATED by scripts/extract-legal.mjs — do not edit by hand.
// Source: ../../../../Nexkeys Website/legal.html
// Legal copy is preserved verbatim (plan N1). Re-run the script if the
// source document is amended.

import type { LegalDocument } from '@/lib/types';

export const LEGAL: LegalDocument = {
  "slug": "legal",
  "title": "Legal Hub",
  "intro": "All NexKeys Agency legal documents in one place. We believe in full transparency with our clients. These documents govern your relationship with us and explain how we handle your data.",
  "meta": [
    {
      "label": "Last Updated",
      "value": "9 March 2026"
    },
    {
      "label": "Jurisdiction",
      "value": "Nigeria"
    },
    {
      "label": "Documents",
      "value": "3 Active Policies"
    },
    {
      "label": "Effective",
      "value": "1 January 2026"
    },
    {
      "label": "Last Revised",
      "value": "9 March 2026"
    },
    {
      "label": "Version",
      "value": "1.0"
    }
  ],
  "sections": [
    {
      "id": "cookie-intro",
      "num": "01",
      "heading": "What Are Cookies?",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Cookies are small text files that are placed on your computer or mobile device by websites that you visit. They are widely used in order to make websites work, or work more efficiently, as well as to provide information to the owners of the site about user behaviour and preferences."
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Cookies are not harmful and do not contain any personally identifiable information by themselves. They are simply identifiers that allow a website to recognise your browser or device on subsequent visits."
            }
          ]
        }
      ]
    },
    {
      "id": "cookie-types",
      "num": "02",
      "heading": "Types of Cookies We Use",
      "blocks": [
        {
          "type": "h3",
          "text": "2.1 Strictly Necessary Cookies"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "These cookies are essential for the NexKeys website to function correctly. They enable core functionalities such as the booking calendar, form submissions, and navigation. These cookies cannot be disabled as the website will not function without them."
            }
          ]
        },
        {
          "type": "table",
          "head": [
            "Cookie Name",
            "Provider",
            "Purpose",
            "Duration"
          ],
          "rows": [
            [
              "__session",
              "NexKeys",
              "Session management for booking form",
              "Session"
            ],
            [
              "firebase:host",
              "Google Firebase",
              "Firebase SDK initialisation and Firestore connectivity",
              "Session"
            ]
          ]
        },
        {
          "type": "h3",
          "text": "2.2 Performance & Analytics Cookies"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "These cookies help us understand how visitors interact with our website by collecting anonymous, aggregated data. They help us improve website performance and user experience. No personally identifiable information is collected through these cookies."
            }
          ]
        },
        {
          "type": "table",
          "head": [
            "Cookie Name",
            "Provider",
            "Purpose",
            "Duration"
          ],
          "rows": [
            [
              "_ga",
              "Google Analytics",
              "Distinguishes unique users using a randomly generated number",
              "2 years"
            ],
            [
              "_ga_*",
              "Google Analytics",
              "Maintains session state across page visits",
              "2 years"
            ]
          ]
        },
        {
          "type": "h3",
          "text": "2.3 Functional Cookies"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Functional cookies enable enhanced functionality and personalisation on the NexKeys website. They may be set by us or by third-party providers whose services we use on our pages."
            }
          ]
        },
        {
          "type": "table",
          "head": [
            "Cookie Name",
            "Provider",
            "Purpose",
            "Duration"
          ],
          "rows": [
            [
              "emailjs_*",
              "EmailJS",
              "Transactional email service state for booking confirmations",
              "1 year"
            ]
          ]
        },
        {
          "type": "h3",
          "text": "2.4 Third-Party Cookies"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Our website loads certain assets from third-party CDNs and services. These may place their own cookies on your device:"
            }
          ]
        },
        {
          "type": "table",
          "head": [
            "Provider",
            "Purpose",
            "Policy Link"
          ],
          "rows": [
            [
              "Google Fonts",
              "Web font delivery",
              "Google Privacy Policy"
            ],
            [
              "Cloudflare CDN",
              "JavaScript library delivery (GSAP, Three.js)",
              "Cloudflare Privacy Policy"
            ],
            [
              "jsDelivr CDN",
              "Lenis smooth scroll library delivery",
              "jsDelivr Privacy Policy"
            ]
          ]
        }
      ]
    },
    {
      "id": "cookie-control",
      "num": "03",
      "heading": "How to Control Cookies",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "You have the right to decide whether to accept or reject cookies. You can exercise your cookie preferences by:"
            }
          ]
        },
        {
          "type": "h3",
          "text": "Browser Settings"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Most web browsers allow you to control cookies through their settings. You can typically find these settings in the “Options,” “Preferences,” or “Privacy” menu of your browser. The following links provide information for major browsers:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "a",
                "text": "Google Chrome",
                "href": "https://support.google.com/chrome/answer/95647"
              }
            ],
            [
              {
                "t": "a",
                "text": "Mozilla Firefox",
                "href": "https://support.mozilla.org/kb/enable-and-disable-cookies-website-preferences"
              }
            ],
            [
              {
                "t": "a",
                "text": "Apple Safari",
                "href": "https://support.apple.com/guide/safari/manage-cookies-sfri11471"
              }
            ],
            [
              {
                "t": "a",
                "text": "Microsoft Edge",
                "href": "https://support.microsoft.com/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09"
              }
            ]
          ]
        },
        {
          "type": "callout",
          "blocks": [
            {
              "type": "p",
              "nodes": [
                {
                  "t": "b",
                  "text": "Please note:"
                },
                {
                  "t": "s",
                  "text": "Disabling strictly necessary cookies will prevent the booking system and contact forms from functioning correctly. We recommend enabling all cookies for the best experience on nexkeysagency.com."
                }
              ]
            }
          ]
        },
        {
          "type": "h3",
          "text": "Opt-Out of Analytics"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "You can opt out of Google Analytics tracking by installing the"
            },
            {
              "t": "a",
              "text": "Google Analytics Opt-out Browser Add-on",
              "href": "https://tools.google.com/dlpage/gaoptout"
            },
            {
              "t": "s",
              "text": "."
            }
          ]
        }
      ]
    },
    {
      "id": "cookie-updates",
      "num": "04",
      "heading": "Updates to This Policy",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "We may update this Cookie Policy from time to time to reflect changes in the cookies we use or for operational, legal, or regulatory reasons. Please revisit this page regularly to stay informed about our use of cookies."
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "For any questions about our use of cookies, please contact us at"
            },
            {
              "t": "a",
              "text": "nexkeysagency@gmail.com",
              "href": "mailto:nexkeysagency@gmail.com"
            },
            {
              "t": "s",
              "text": "."
            }
          ]
        }
      ]
    }
  ]
};
