// GENERATED by scripts/extract-legal.mjs — do not edit by hand.
// Source: ../../../../Nexkeys Website/privacy.html
// Legal copy is preserved verbatim (plan N1). Re-run the script if the
// source document is amended.

import type { LegalDocument } from '@/lib/types';

export const PRIVACY: LegalDocument = {
  "slug": "privacy",
  "title": "Privacy Policy",
  "intro": "NexKeys Agency is committed to protecting your privacy. This Policy explains in clear, plain language what personal data we collect, how we use it, who we share it with, and the rights you hold over your information.",
  "meta": [
    {
      "label": "Effective Date",
      "value": "1 January 2026"
    },
    {
      "label": "Last Revised",
      "value": "9 March 2026"
    },
    {
      "label": "Compliance",
      "value": "NDPR 2019 (Nigeria)"
    },
    {
      "label": "Version",
      "value": "1.2"
    }
  ],
  "sections": [
    {
      "id": "privacy-intro",
      "num": "01",
      "heading": "Introduction",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys Agency (“NexKeys,” “we,” “us,” or “our”) respects your privacy and is committed to protecting the personal information you share with us. This Privacy Policy describes our practices in connection with information collected through our website, booking system, contact forms, and in the course of project engagements."
            }
          ]
        },
        {
          "type": "callout",
          "blocks": [
            {
              "type": "p",
              "nodes": [
                {
                  "t": "b",
                  "text": "By using the NexKeys website or engaging our services, you consent to the collection and use of your personal information as described in this Policy."
                },
                {
                  "t": "s",
                  "text": "If you do not agree, please discontinue use of our Platform immediately."
                }
              ]
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "This Policy is compliant with the Nigeria Data Protection Regulation 2019 (NDPR) and is aligned with international best practices including the General Data Protection Regulation (GDPR) where applicable to our international clients."
            }
          ]
        }
      ]
    },
    {
      "id": "data-controller",
      "num": "02",
      "heading": "Data Controller",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "For the purposes of applicable data protection law, the Data Controller responsible for your personal information is:"
            }
          ]
        },
        {
          "type": "contactCard",
          "rows": [
            {
              "icon": "🏢",
              "nodes": [
                {
                  "t": "b",
                  "text": "NexKeys Agency"
                },
                {
                  "t": "br"
                },
                {
                  "t": "s",
                  "text": "Lagos, Federal Republic of Nigeria"
                }
              ]
            },
            {
              "icon": "✉",
              "nodes": [
                {
                  "t": "s",
                  "text": "Data enquiries:"
                },
                {
                  "t": "a",
                  "text": "nexkeysagency@gmail.com",
                  "href": "mailto:nexkeysagency@gmail.com"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "data-collected",
      "num": "03",
      "heading": "Data We Collect",
      "blocks": [
        {
          "type": "h3",
          "text": "3.1 Information You Provide Directly"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "We collect personal information that you voluntarily provide to us, including when you:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "Complete a booking form to schedule a discovery call (name, email address, phone number, timezone, project notes)."
              }
            ],
            [
              {
                "t": "s",
                "text": "Submit a project brief or contact form (name, email, company name, service requirements, project description)."
              }
            ],
            [
              {
                "t": "s",
                "text": "Enter into a project agreement or contract with NexKeys."
              }
            ],
            [
              {
                "t": "s",
                "text": "Communicate with us via email, phone, or social media."
              }
            ]
          ]
        },
        {
          "type": "h3",
          "text": "3.2 Information Collected Automatically"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "When you visit our website, we may automatically collect certain technical information, including:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "b",
                "text": "Device & Browser Data:"
              },
              {
                "t": "s",
                "text": "Browser type and version, operating system, device type, screen resolution."
              }
            ],
            [
              {
                "t": "b",
                "text": "Usage Data:"
              },
              {
                "t": "s",
                "text": "Pages visited, time spent on pages, navigation paths, referring URLs, and click behaviour."
              }
            ],
            [
              {
                "t": "b",
                "text": "Technical Identifiers:"
              },
              {
                "t": "s",
                "text": "IP address, approximate geographic location (country/city level), session identifiers."
              }
            ]
          ]
        },
        {
          "type": "h3",
          "text": "3.3 Information from Third-Party Sources"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "We may receive limited information about you from third-party platforms such as LinkedIn or social media if you contact us through those channels. We do not purchase personal data from data brokers."
            }
          ]
        },
        {
          "type": "callout",
          "blocks": [
            {
              "type": "p",
              "nodes": [
                {
                  "t": "b",
                  "text": "We do not collect sensitive personal data"
                },
                {
                  "t": "s",
                  "text": "(such as financial account numbers, government identification numbers, biometric data, or health information) through our website or booking system."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "how-we-use",
      "num": "04",
      "heading": "How We Use Your Data",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys Agency uses the personal data we collect for the following purposes:"
            }
          ]
        },
        {
          "type": "table",
          "head": [
            "Purpose",
            "Data Used"
          ],
          "rows": [
            [
              "Processing and confirming discovery call bookings",
              "Name, email, phone, timezone, notes"
            ],
            [
              "Responding to enquiries and project briefs",
              "Name, email, company, project description"
            ],
            [
              "Delivering project services and communicating progress",
              "All project-related contact and technical data"
            ],
            [
              "Sending booking confirmations and reminders",
              "Name, email, booking details"
            ],
            [
              "Improving our website and services",
              "Anonymised usage and analytics data"
            ],
            [
              "Complying with legal and regulatory obligations",
              "As required by applicable law"
            ],
            [
              "Protecting against fraud and security threats",
              "Technical identifiers, IP address"
            ]
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "We do not use your personal data for automated decision-making or profiling that produces legal or similarly significant effects on you."
            }
          ]
        }
      ]
    },
    {
      "id": "legal-basis",
      "num": "05",
      "heading": "Legal Basis for Processing",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Under the NDPR and applicable data protection law, we process your personal data on the following legal grounds:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "b",
                "text": "Consent:"
              },
              {
                "t": "s",
                "text": "Where you have given clear consent for us to process your data for a specific purpose (e.g., scheduling a discovery call or submitting a brief)."
              }
            ],
            [
              {
                "t": "b",
                "text": "Contractual Necessity:"
              },
              {
                "t": "s",
                "text": "Where processing is necessary for the performance of a contract with you, or to take steps at your request prior to entering a contract."
              }
            ],
            [
              {
                "t": "b",
                "text": "Legitimate Interests:"
              },
              {
                "t": "s",
                "text": "Where processing is necessary for our legitimate business interests (e.g., website analytics, fraud prevention, portfolio display), and these interests are not overridden by your rights."
              }
            ],
            [
              {
                "t": "b",
                "text": "Legal Obligation:"
              },
              {
                "t": "s",
                "text": "Where processing is necessary to comply with a legal obligation to which NexKeys is subject."
              }
            ]
          ]
        }
      ]
    },
    {
      "id": "cookies",
      "num": "06",
      "heading": "Cookies & Tracking Technologies",
      "blocks": [
        {
          "type": "h3",
          "text": "6.1 What Are Cookies?"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Cookies are small text files placed on your device by websites you visit. They are widely used to make websites work efficiently, improve user experience, and provide analytical information to site owners."
            }
          ]
        },
        {
          "type": "h3",
          "text": "6.2 Types of Cookies We Use"
        },
        {
          "type": "table",
          "head": [
            "Category",
            "Purpose",
            "Duration"
          ],
          "rows": [
            [
              "Strictly Necessary",
              "Essential for the website to function. Cannot be disabled.",
              "Session"
            ],
            [
              "Performance / Analytics",
              "Help us understand how visitors interact with our website (e.g., pages visited, time on site). All data is anonymised.",
              "Up to 2 years"
            ],
            [
              "Functional",
              "Remember preferences and settings to improve your experience.",
              "Up to 1 year"
            ],
            [
              "Third-Party",
              "Placed by embedded services such as Firebase and EmailJS for booking functionality.",
              "Varies"
            ]
          ]
        },
        {
          "type": "h3",
          "text": "6.3 Managing Cookies"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "You can control and delete cookies through your browser settings. Disabling strictly necessary cookies may affect the functionality of our booking system and contact forms. For more information on managing cookies, visit"
            },
            {
              "t": "a",
              "text": "allaboutcookies.org",
              "href": "https://www.allaboutcookies.org"
            },
            {
              "t": "s",
              "text": "."
            }
          ]
        }
      ]
    },
    {
      "id": "analytics",
      "num": "07",
      "heading": "Analytics",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys Agency may use web analytics tools to help us understand how our website is used and to improve user experience. Any analytics data collected is aggregated and anonymised — it is not used to identify individual users."
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "If we implement Google Analytics or a similar service, we will configure it to anonymise IP addresses and will update this Policy accordingly. You may opt out of analytics tracking by:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "Installing the"
              },
              {
                "t": "a",
                "text": "Google Analytics Opt-out Browser Add-on",
                "href": "https://tools.google.com/dlpage/gaoptout"
              },
              {
                "t": "s",
                "text": "."
              }
            ],
            [
              {
                "t": "s",
                "text": "Enabling “Do Not Track” in your browser settings."
              }
            ],
            [
              {
                "t": "s",
                "text": "Using a privacy-focused browser or extension."
              }
            ]
          ]
        }
      ]
    },
    {
      "id": "third-parties",
      "num": "08",
      "heading": "Third-Party Services",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Our website and booking system integrate with the following third-party services. Each operates under its own privacy policy:"
            }
          ]
        },
        {
          "type": "table",
          "head": [
            "Service",
            "Purpose",
            "Privacy Policy"
          ],
          "rows": [
            [
              "Google Firebase / Firestore",
              "Booking data storage and availability management",
              "firebase.google.com/support/privacy"
            ],
            [
              "EmailJS",
              "Transactional email delivery for booking confirmations",
              "emailjs.com/legal/privacy-policy"
            ],
            [
              "Google Fonts",
              "Web typography (Bebas Neue, Syne, DM Sans)",
              "policies.google.com/privacy"
            ],
            [
              "Cloudflare CDN",
              "GSAP and Three.js library delivery",
              "cloudflare.com/privacypolicy"
            ]
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys Agency does not sell, rent, or trade your personal information to third parties for marketing purposes."
            }
          ]
        }
      ]
    },
    {
      "id": "data-sharing",
      "num": "09",
      "heading": "Data Sharing & Disclosure",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "We may share your personal data only in the following limited circumstances:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "b",
                "text": "Service Providers:"
              },
              {
                "t": "s",
                "text": "Trusted third-party vendors who assist in delivering our services (such as those listed in Section 8), bound by contractual data protection obligations."
              }
            ],
            [
              {
                "t": "b",
                "text": "Legal Requirements:"
              },
              {
                "t": "s",
                "text": "Where we are required by law, court order, or government authority to disclose your information."
              }
            ],
            [
              {
                "t": "b",
                "text": "Protection of Rights:"
              },
              {
                "t": "s",
                "text": "Where disclosure is necessary to protect the rights, property, or safety of NexKeys Agency, our clients, or the public."
              }
            ],
            [
              {
                "t": "b",
                "text": "Business Transfers:"
              },
              {
                "t": "s",
                "text": "In the event of a merger, acquisition, or sale of assets, your data may be transferred to the successor entity, subject to the same privacy protections."
              }
            ]
          ]
        },
        {
          "type": "callout",
          "blocks": [
            {
              "type": "p",
              "nodes": [
                {
                  "t": "b",
                  "text": "We will never sell your personal data to third parties."
                },
                {
                  "t": "s",
                  "text": "We will never share your data with advertisers or use it for purposes unrelated to delivering our services."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "international",
      "num": "10",
      "heading": "International Data Transfers",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "As NexKeys Agency serves clients globally and uses services such as Firebase and EmailJS, your data may be processed on servers located outside Nigeria. Where such transfers occur, we ensure that appropriate safeguards are in place, including:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "Engaging only processors that maintain adequate data protection standards."
              }
            ],
            [
              {
                "t": "s",
                "text": "Ensuring compliance with NDPR transfer rules and, where applicable, GDPR Standard Contractual Clauses."
              }
            ]
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "By submitting your information through our website, you acknowledge and consent to such transfers."
            }
          ]
        }
      ]
    },
    {
      "id": "security",
      "num": "11",
      "heading": "Security Practices",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys Agency implements reasonable and appropriate technical and organisational security measures to protect your personal data against unauthorised access, disclosure, alteration, or destruction. These measures include:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "HTTPS encryption for all data transmitted through our website and booking system."
              }
            ],
            [
              {
                "t": "s",
                "text": "Access controls and role-based permissions for systems that store personal data."
              }
            ],
            [
              {
                "t": "s",
                "text": "Firebase Firestore security rules that restrict read and write access to only authorised operations."
              }
            ],
            [
              {
                "t": "s",
                "text": "Regular review and updating of security practices in line with industry standards."
              }
            ]
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "While we take data security seriously, no method of transmission over the internet or electronic storage is completely secure. We cannot guarantee absolute security, and you share personal data at your own risk. In the event of a data breach that is likely to result in risk to your rights and freedoms, we will notify you and the relevant supervisory authority as required by law."
            }
          ]
        }
      ]
    },
    {
      "id": "retention",
      "num": "12",
      "heading": "Data Retention",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "We retain personal data only for as long as is necessary to fulfil the purposes for which it was collected, or as required by applicable law. Our retention periods are as follows:"
            }
          ]
        },
        {
          "type": "table",
          "head": [
            "Data Category",
            "Retention Period",
            "Reason"
          ],
          "rows": [
            [
              "Booking records",
              "2 years from booking date",
              "Business records, dispute resolution"
            ],
            [
              "Project correspondence",
              "5 years from project completion",
              "Legal and contractual obligations"
            ],
            [
              "Contact form submissions",
              "12 months if no engagement follows",
              "Follow-up and service improvement"
            ],
            [
              "Invoicing and payment records",
              "7 years",
              "Regulatory and tax compliance"
            ],
            [
              "Website analytics (anonymised)",
              "26 months",
              "Performance analysis"
            ]
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Once data is no longer required, it is securely deleted or anonymised in accordance with our data disposal procedures."
            }
          ]
        }
      ]
    },
    {
      "id": "your-rights",
      "num": "13",
      "heading": "Your Rights",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Under the Nigeria Data Protection Regulation (NDPR) and applicable international data protection law, you have the following rights regarding your personal data:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "b",
                "text": "Right of Access:"
              },
              {
                "t": "s",
                "text": "You have the right to request a copy of the personal data we hold about you."
              }
            ],
            [
              {
                "t": "b",
                "text": "Right to Rectification:"
              },
              {
                "t": "s",
                "text": "You have the right to request that we correct any inaccurate or incomplete personal data."
              }
            ],
            [
              {
                "t": "b",
                "text": "Right to Erasure:"
              },
              {
                "t": "s",
                "text": "You have the right to request deletion of your personal data where there is no lawful basis for continued processing."
              }
            ],
            [
              {
                "t": "b",
                "text": "Right to Restriction:"
              },
              {
                "t": "s",
                "text": "You have the right to request that we restrict the processing of your data in certain circumstances."
              }
            ],
            [
              {
                "t": "b",
                "text": "Right to Data Portability:"
              },
              {
                "t": "s",
                "text": "Where processing is based on consent or contract, you have the right to receive your data in a structured, commonly used, and machine-readable format."
              }
            ],
            [
              {
                "t": "b",
                "text": "Right to Object:"
              },
              {
                "t": "s",
                "text": "You have the right to object to processing based on legitimate interests, including direct marketing."
              }
            ],
            [
              {
                "t": "b",
                "text": "Right to Withdraw Consent:"
              },
              {
                "t": "s",
                "text": "Where processing is based on your consent, you may withdraw that consent at any time without affecting the lawfulness of prior processing."
              }
            ]
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "To exercise any of these rights, please contact us at"
            },
            {
              "t": "a",
              "text": "nexkeysagency@gmail.com",
              "href": "mailto:nexkeysagency@gmail.com"
            },
            {
              "t": "s",
              "text": "with the subject lineDATA REQUEST — [Your Name]. We will respond within thirty (30) days. We may need to verify your identity before processing your request."
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "If you are dissatisfied with our response, you have the right to lodge a complaint with the National Information Technology Development Agency (NITDA), which is the supervisory authority for data protection in Nigeria."
            }
          ]
        }
      ]
    },
    {
      "id": "children",
      "num": "14",
      "heading": "Children’s Privacy",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys Agency services are intended for businesses and adult professionals. Our website and services are not directed at individuals under the age of 18. We do not knowingly collect personal data from minors. If we become aware that we have inadvertently received personal data from a person under 18, we will delete it promptly. If you believe we may have collected data from a minor, please contact us immediately at"
            },
            {
              "t": "a",
              "text": "nexkeysagency@gmail.com",
              "href": "mailto:nexkeysagency@gmail.com"
            },
            {
              "t": "s",
              "text": "."
            }
          ]
        }
      ]
    },
    {
      "id": "changes",
      "num": "15",
      "heading": "Changes to This Policy",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys Agency may update this Privacy Policy from time to time to reflect changes in our data practices, legal obligations, or service offerings. Material changes will be communicated via a prominent notice on our website prior to the changes taking effect."
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "The “Last Revised” date at the top of this document reflects the most recent update. We encourage you to review this Policy periodically. Your continued use of our Platform following the effective date of any revision constitutes your acceptance of the updated Policy."
            }
          ]
        }
      ]
    },
    {
      "id": "contact-privacy",
      "num": "16",
      "heading": "Contact",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "For all privacy-related enquiries, data access requests, or complaints, please contact our team:"
            }
          ]
        },
        {
          "type": "contactCard",
          "rows": [
            {
              "icon": "🏢",
              "nodes": [
                {
                  "t": "b",
                  "text": "NexKeys Agency — Privacy Team"
                },
                {
                  "t": "br"
                },
                {
                  "t": "s",
                  "text": "Lagos, Nigeria"
                }
              ]
            },
            {
              "icon": "✉",
              "nodes": [
                {
                  "t": "s",
                  "text": "Email:"
                },
                {
                  "t": "a",
                  "text": "nexkeysagency@gmail.com",
                  "href": "mailto:nexkeysagency@gmail.com"
                }
              ]
            },
            {
              "icon": "📞",
              "nodes": [
                {
                  "t": "s",
                  "text": "Phone:"
                },
                {
                  "t": "a",
                  "text": "+234 803 300 4474",
                  "href": "tel:+2348033004474"
                }
              ]
            },
            {
              "icon": "⏱",
              "nodes": [
                {
                  "t": "s",
                  "text": "Response time: Within 30 calendar days"
                }
              ]
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "All data requests must be submitted via email with the subject lineDATA REQUEST — [Your Name]for fastest processing."
            }
          ]
        }
      ]
    }
  ]
};
