// GENERATED by scripts/extract-legal.mjs — do not edit by hand.
// Source: ../../../../Nexkeys Website/terms.html
// Legal copy is preserved verbatim (plan N1). Re-run the script if the
// source document is amended.

import type { LegalDocument } from '@/lib/types';

export const TERMS: LegalDocument = {
  "slug": "terms",
  "title": "Terms & Conditions",
  "intro": "These Terms and Conditions govern your access to and use of NexKeys Agency services, digital platforms, and all associated project engagements. Please read them carefully before proceeding.",
  "meta": [
    {
      "label": "Effective Date",
      "value": "1 January 2026"
    },
    {
      "label": "Last Revised",
      "value": "9 March 2026"
    },
    {
      "label": "Jurisdiction",
      "value": "Federal Republic of Nigeria"
    },
    {
      "label": "Version",
      "value": "1.2"
    }
  ],
  "sections": [
    {
      "id": "introduction",
      "num": "01",
      "heading": "Introduction",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Welcome to NexKeys Agency (“NexKeys,” “we,” “us,” or “our”). NexKeys Agency is a professional software and digital services agency registered and operating under the laws of the Federal Republic of Nigeria. We provide end-to-end digital solutions including web application development, mobile application development, UI/UX design, landing page creation, AI integration, automation engineering, and technical team augmentation services."
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "These Terms and Conditions (“Terms”) constitute a legally binding agreement between NexKeys Agency and any individual, company, or entity (“Client,” “User,” or “you”) that accesses our website, engages our services, or enters into a project agreement with us."
            }
          ]
        },
        {
          "type": "callout",
          "blocks": [
            {
              "type": "p",
              "nodes": [
                {
                  "t": "b",
                  "text": "By accessing this website or engaging NexKeys Agency services, you acknowledge that you have read, understood, and agree to be bound by these Terms in their entirety."
                },
                {
                  "t": "s",
                  "text": "If you do not agree, you must immediately cease all use of our platforms and services."
                }
              ]
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "These Terms should be read alongside our"
            },
            {
              "t": "a",
              "text": "Privacy Policy",
              "href": "privacy.html"
            },
            {
              "t": "s",
              "text": "and any individual Statement of Work, proposal, or project agreement entered into between the parties."
            }
          ]
        }
      ]
    },
    {
      "id": "definitions",
      "num": "02",
      "heading": "Definitions",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "For the purposes of these Terms, the following definitions apply:"
            }
          ]
        },
        {
          "type": "table",
          "head": [
            "Term",
            "Definition"
          ],
          "rows": [
            [
              "Agency / NexKeys",
              "NexKeys Agency, including its founders, employees, contractors, and authorised representatives."
            ],
            [
              "Client / You",
              "Any individual, business entity, or organisation that engages or seeks to engage NexKeys Agency for services."
            ],
            [
              "Services",
              "All digital, technical, creative, and consulting services offered by NexKeys Agency, whether delivered remotely or on-site."
            ],
            [
              "Deliverables",
              "Any tangible or digital output produced by NexKeys Agency in the course of a project engagement, including but not limited to code, designs, documentation, and deployed applications."
            ],
            [
              "Project Agreement",
              "A Statement of Work (SOW), proposal, or written agreement that defines the scope, timeline, payment structure, and specific terms of a given engagement."
            ],
            [
              "Intellectual Property (IP)",
              "All creative works, inventions, code, designs, algorithms, trade secrets, brand assets, and any other proprietary material created in connection with the Services."
            ],
            [
              "Confidential Information",
              "Any non-public information disclosed by either party in connection with a project engagement, including technical specifications, business strategy, financial data, and client data."
            ],
            [
              "Platform",
              "The NexKeys Agency website at nexkeysagency.com and any associated web properties or applications operated by NexKeys."
            ]
          ]
        }
      ]
    },
    {
      "id": "services",
      "num": "03",
      "heading": "Services",
      "blocks": [
        {
          "type": "h3",
          "text": "3.1 Scope of Services"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys Agency provides the following categories of professional digital services:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "b",
                "text": "Web Application & Business Website Development"
              },
              {
                "t": "s",
                "text": "— Full-stack development of SaaS platforms, business websites, portals, and custom web systems."
              }
            ],
            [
              {
                "t": "b",
                "text": "Mobile Application Development"
              },
              {
                "t": "s",
                "text": "— Cross-platform iOS and Android applications built with React Native and related technologies."
              }
            ],
            [
              {
                "t": "b",
                "text": "UI/UX Design"
              },
              {
                "t": "s",
                "text": "— User research, wireframing, design systems, interactive prototyping, and experience strategy."
              }
            ],
            [
              {
                "t": "b",
                "text": "Landing Page Development"
              },
              {
                "t": "s",
                "text": "— Conversion-optimised marketing and product landing pages."
              }
            ],
            [
              {
                "t": "b",
                "text": "AI Integration & Automation"
              },
              {
                "t": "s",
                "text": "— Process automation workflows, AI-powered features, and intelligent system integrations."
              }
            ],
            [
              {
                "t": "b",
                "text": "Technical Team as a Service"
              },
              {
                "t": "s",
                "text": "— Embedded technical resources, on-demand engineering support, and project management services."
              }
            ]
          ]
        },
        {
          "type": "h3",
          "text": "3.2 Service Delivery"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "All services are delivered remotely unless otherwise agreed in writing. Specific deliverables, timelines, and acceptance criteria are defined in individual Project Agreements. NexKeys reserves the right to utilise qualified subcontractors for portions of any project, subject to the same confidentiality obligations outlined in these Terms."
            }
          ]
        },
        {
          "type": "h3",
          "text": "3.3 Discovery Call"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys offers free 30-minute discovery calls to prospective clients. A discovery call does not constitute a binding service agreement. No work will commence until a formal Project Agreement is signed by both parties and an initial payment is received, as applicable."
            }
          ]
        }
      ]
    },
    {
      "id": "user-responsibilities",
      "num": "04",
      "heading": "User Responsibilities",
      "blocks": [
        {
          "type": "h3",
          "text": "4.1 Accurate Information"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "You agree to provide NexKeys Agency with accurate, current, and complete information as required for the performance of services. Providing false, misleading, or incomplete information that materially affects project delivery may result in additional costs or termination of the engagement."
            }
          ]
        },
        {
          "type": "h3",
          "text": "4.2 Timely Feedback & Approvals"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "You are responsible for providing timely feedback, approvals, and necessary project assets (including but not limited to copy, images, brand guidelines, third-party credentials, and access permissions). Delays caused by the Client’s failure to provide required inputs may result in revised timelines and additional charges."
            }
          ]
        },
        {
          "type": "h3",
          "text": "4.3 Authorised Use"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "You represent and warrant that:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "You have the full legal authority to enter into agreements with NexKeys Agency on behalf of yourself or your organisation."
              }
            ],
            [
              {
                "t": "s",
                "text": "All content, data, and materials you provide to NexKeys do not infringe upon any third-party intellectual property rights, privacy rights, or applicable laws."
              }
            ],
            [
              {
                "t": "s",
                "text": "You will use all deliverables solely for lawful purposes and in compliance with all applicable laws and regulations."
              }
            ]
          ]
        },
        {
          "type": "h3",
          "text": "4.4 Account Security"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Where project collaboration tools, accounts, or credentials are shared, you are responsible for maintaining the confidentiality of any access credentials provided to you and for all activities that occur under those credentials."
            }
          ]
        }
      ]
    },
    {
      "id": "acceptable-use",
      "num": "05",
      "heading": "Acceptable Use Policy",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "By engaging NexKeys Agency services or accessing our Platform, you agree not to use our services, deliverables, or platform to:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "Develop, distribute, or deploy software intended to cause harm, deceive, defraud, or unlawfully surveil any person or organisation."
              }
            ],
            [
              {
                "t": "s",
                "text": "Transmit, store, or process content that is unlawful, defamatory, obscene, discriminatory, or that violates the rights of third parties."
              }
            ],
            [
              {
                "t": "s",
                "text": "Circumvent, disable, or interfere with security features or access controls of any platform, system, or network."
              }
            ],
            [
              {
                "t": "s",
                "text": "Conduct or facilitate spamming, phishing, or the distribution of malicious software."
              }
            ],
            [
              {
                "t": "s",
                "text": "Violate any applicable local, national, or international law or regulation, including data protection and privacy laws."
              }
            ],
            [
              {
                "t": "s",
                "text": "Engage in any activity that could damage the reputation, brand, or intellectual property of NexKeys Agency."
              }
            ],
            [
              {
                "t": "s",
                "text": "Reverse-engineer, decompile, or disassemble any NexKeys proprietary tools, processes, or software not covered under your Project Agreement."
              }
            ]
          ]
        },
        {
          "type": "callout",
          "blocks": [
            {
              "type": "p",
              "nodes": [
                {
                  "t": "b",
                  "text": "Violation of this Acceptable Use Policy may result in immediate suspension of services, forfeiture of payments made, and legal action where warranted."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "intellectual-property",
      "num": "06",
      "heading": "Intellectual Property Rights",
      "blocks": [
        {
          "type": "h3",
          "text": "6.1 Client IP Transfer"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Upon receipt of full payment for a completed project, NexKeys Agency assigns to the Client all rights, title, and interest in the custom deliverables specifically created for that engagement, including source code, design assets, and documentation, unless otherwise specified in the Project Agreement."
            }
          ]
        },
        {
          "type": "h3",
          "text": "6.2 NexKeys Retained IP"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Notwithstanding the above, NexKeys Agency retains all rights to:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "Pre-existing proprietary tools, frameworks, libraries, templates, boilerplates, and development methodologies used in the delivery of services."
              }
            ],
            [
              {
                "t": "s",
                "text": "General knowledge, skills, expertise, and know-how developed or refined in the course of any engagement."
              }
            ],
            [
              {
                "t": "s",
                "text": "Any third-party open-source components incorporated into deliverables, which remain subject to their respective licences."
              }
            ]
          ]
        },
        {
          "type": "h3",
          "text": "6.3 Licence to Use"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Where full ownership transfer is not specified in the Project Agreement, NexKeys grants the Client a perpetual, non-exclusive, non-transferable licence to use the deliverables solely for the Client’s internal business purposes."
            }
          ]
        },
        {
          "type": "h3",
          "text": "6.4 Portfolio Rights"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Unless expressly prohibited in writing by the Client prior to project commencement, NexKeys Agency reserves the right to display completed work in its portfolio, case studies, marketing materials, and social media channels. Confidential business logic or sensitive data will not be disclosed."
            }
          ]
        },
        {
          "type": "h3",
          "text": "6.5 NexKeys Brand Assets"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "The NexKeys Agency name, logo, tagline, and all associated brand assets are the exclusive intellectual property of NexKeys Agency. You may not use, reproduce, or imply affiliation with NexKeys without prior written authorisation."
            }
          ]
        }
      ]
    },
    {
      "id": "payments",
      "num": "07",
      "heading": "Payment & Project Terms",
      "blocks": [
        {
          "type": "h3",
          "text": "7.1 Project Pricing"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "All project pricing is agreed upon in advance within a formal Project Agreement or proposal. Prices are quoted in the agreed currency and are exclusive of applicable taxes unless stated otherwise."
            }
          ]
        },
        {
          "type": "h3",
          "text": "7.2 Payment Schedule"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Unless otherwise specified in the Project Agreement, the standard payment schedule is as follows:"
            }
          ]
        },
        {
          "type": "table",
          "head": [
            "Milestone",
            "Payment Due"
          ],
          "rows": [
            [
              "Project Kickoff / Commencement",
              "50% of agreed project fee"
            ],
            [
              "Delivery of First Major Milestone",
              "25% of agreed project fee"
            ],
            [
              "Final Delivery & Client Acceptance",
              "Remaining 25% of project fee"
            ]
          ]
        },
        {
          "type": "h3",
          "text": "7.3 Late Payment"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Invoices not settled within fourteen (14) calendar days of the due date will attract a late payment charge of 2% per month on the outstanding balance. NexKeys reserves the right to suspend all project work until outstanding balances are cleared."
            }
          ]
        },
        {
          "type": "h3",
          "text": "7.4 Scope Changes"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Any request to expand, modify, or alter the agreed project scope after commencement constitutes a change order. Change orders will be assessed and quoted separately. NexKeys will not implement out-of-scope work without a written change order agreement and payment confirmation."
            }
          ]
        },
        {
          "type": "h3",
          "text": "7.5 Refunds"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Given the bespoke nature of our services, initial deposits are non-refundable. Where NexKeys fails to deliver agreed milestones due to our own default, a proportionate refund may be negotiated in good faith. Refund requests arising from Client-caused delays, scope changes, or change of mind will not be entertained."
            }
          ]
        },
        {
          "type": "h3",
          "text": "7.6 Retainer Engagements"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "For ongoing retainer or maintenance arrangements, fees are payable monthly in advance. Retainer agreements may be terminated by either party with thirty (30) days’ written notice."
            }
          ]
        }
      ]
    },
    {
      "id": "confidentiality",
      "num": "08",
      "heading": "Confidentiality",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Both parties acknowledge that in the course of a project engagement, each may disclose Confidential Information to the other. Each party agrees to:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "Hold all Confidential Information of the other party in strict confidence and not disclose it to any third party without prior written consent."
              }
            ],
            [
              {
                "t": "s",
                "text": "Use Confidential Information solely for the purposes of the project engagement."
              }
            ],
            [
              {
                "t": "s",
                "text": "Apply reasonable security measures to protect Confidential Information, no less stringent than those used to protect its own confidential information."
              }
            ]
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "These obligations shall survive the termination of any project agreement for a period of three (3) years. NexKeys Agency may disclose Confidential Information where required by applicable law, court order, or regulatory authority, provided reasonable prior notice is given to the Client where legally permissible."
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Upon request, NexKeys Agency is willing to execute a separate Non-Disclosure Agreement (NDA) prior to any project discussion. Please contact us at"
            },
            {
              "t": "a",
              "text": "nexkeysagency@gmail.com",
              "href": "mailto:nexkeysagency@gmail.com"
            },
            {
              "t": "s",
              "text": "to request an NDA."
            }
          ]
        }
      ]
    },
    {
      "id": "warranties",
      "num": "09",
      "heading": "Warranties & Disclaimers",
      "blocks": [
        {
          "type": "h3",
          "text": "9.1 NexKeys Warranties"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys Agency warrants that:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "Services will be performed by qualified professionals with reasonable skill and care."
              }
            ],
            [
              {
                "t": "s",
                "text": "Deliverables will substantially conform to the agreed specifications in the Project Agreement."
              }
            ],
            [
              {
                "t": "s",
                "text": "We hold all necessary rights to provide the services and will not knowingly infringe third-party intellectual property rights."
              }
            ]
          ]
        },
        {
          "type": "h3",
          "text": "9.2 Disclaimers"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "To the maximum extent permitted by applicable law, NexKeys Agency makes no warranty or representation that:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "Deliverables will be entirely error-free or operate without interruption under all conditions."
              }
            ],
            [
              {
                "t": "s",
                "text": "Any specific business outcome, revenue growth, or performance metric will be achieved as a result of our services."
              }
            ],
            [
              {
                "t": "s",
                "text": "Third-party platforms, APIs, or services integrated into deliverables will remain available, functional, or free from changes."
              }
            ]
          ]
        },
        {
          "type": "callout",
          "blocks": [
            {
              "type": "p",
              "nodes": [
                {
                  "t": "b",
                  "text": "The Platform and all informational content are provided on an “as is” and “as available” basis without warranties of any kind, either express or implied."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "liability",
      "num": "10",
      "heading": "Limitation of Liability",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "To the fullest extent permitted by applicable law, NexKeys Agency shall not be liable for any:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "Indirect, incidental, special, consequential, or punitive damages of any kind."
              }
            ],
            [
              {
                "t": "s",
                "text": "Loss of profits, revenue, data, goodwill, or business opportunities."
              }
            ],
            [
              {
                "t": "s",
                "text": "Damages arising from the Client’s own use, misuse, or modification of deliverables after final delivery."
              }
            ],
            [
              {
                "t": "s",
                "text": "Third-party claims arising from content, data, or instructions provided by the Client."
              }
            ],
            [
              {
                "t": "s",
                "text": "Downtime, data loss, or service disruption caused by third-party hosting providers, APIs, or infrastructure."
              }
            ]
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "In all circumstances, NexKeys Agency’s maximum aggregate liability for any claim arising out of or related to a project engagement shall not exceed the total fees paid by the Client to NexKeys in the three (3) months immediately preceding the event giving rise to the claim."
            }
          ]
        }
      ]
    },
    {
      "id": "indemnification",
      "num": "11",
      "heading": "Indemnification",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "You agree to defend, indemnify, and hold harmless NexKeys Agency and its officers, directors, employees, and contractors from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or in connection with:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "Your violation of these Terms or any applicable law or regulation."
              }
            ],
            [
              {
                "t": "s",
                "text": "Your use of deliverables in a manner not authorised by the Project Agreement."
              }
            ],
            [
              {
                "t": "s",
                "text": "Content, data, or instructions you provide to NexKeys that infringe any third-party right."
              }
            ],
            [
              {
                "t": "s",
                "text": "Any misrepresentation made by you in connection with your engagement with NexKeys."
              }
            ]
          ]
        }
      ]
    },
    {
      "id": "termination",
      "num": "12",
      "heading": "Termination",
      "blocks": [
        {
          "type": "h3",
          "text": "12.1 Termination by Client"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "A Client may terminate an ongoing project engagement by providing fourteen (14) days’ written notice to NexKeys Agency. Upon termination, the Client shall pay for all work completed up to the termination date, including a reasonable amount for work in progress. The initial deposit is non-refundable."
            }
          ]
        },
        {
          "type": "h3",
          "text": "12.2 Termination by NexKeys"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys Agency reserves the right to immediately terminate any engagement if the Client:"
            }
          ]
        },
        {
          "type": "ul",
          "items": [
            [
              {
                "t": "s",
                "text": "Fails to make payment within fourteen (14) days of a payment due date."
              }
            ],
            [
              {
                "t": "s",
                "text": "Engages in conduct that violates these Terms, the Acceptable Use Policy, or any applicable law."
              }
            ],
            [
              {
                "t": "s",
                "text": "Provides materially false or misleading information."
              }
            ],
            [
              {
                "t": "s",
                "text": "Engages in abusive, threatening, or harassing behaviour towards NexKeys personnel."
              }
            ]
          ]
        },
        {
          "type": "h3",
          "text": "12.3 Effect of Termination"
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Upon termination, all licences granted to either party cease immediately. NexKeys will deliver all completed work to the Client upon receipt of all outstanding payments. Clauses relating to Confidentiality, Intellectual Property, Liability, and Governing Law survive termination indefinitely."
            }
          ]
        }
      ]
    },
    {
      "id": "disputes",
      "num": "13",
      "heading": "Dispute Resolution",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "In the event of a dispute arising from or in connection with these Terms or any project engagement, both parties agree to first attempt resolution through good-faith negotiation within thirty (30) days of written notice of the dispute."
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "If the dispute cannot be resolved through negotiation, both parties agree to submit to mediation before pursuing any formal legal proceedings. Mediation shall be conducted in Lagos, Nigeria, under rules mutually agreed upon by the parties."
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Only if mediation fails shall either party be entitled to pursue binding arbitration or litigation through the courts of competent jurisdiction in Nigeria."
            }
          ]
        }
      ]
    },
    {
      "id": "governing-law",
      "num": "14",
      "heading": "Governing Law",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "These Terms and all project agreements shall be governed by and construed in accordance with the laws of the Federal Republic of Nigeria. Both parties irrevocably submit to the exclusive jurisdiction of the courts of Lagos State, Nigeria, for the resolution of any disputes that cannot be resolved through the mechanisms described in Section 13."
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "Where a Client is located in a different jurisdiction, nothing in this clause limits NexKeys Agency’s right to seek injunctive relief or enforcement in that jurisdiction where necessary to protect intellectual property or confidential information."
            }
          ]
        }
      ]
    },
    {
      "id": "amendments",
      "num": "15",
      "heading": "Amendments",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "NexKeys Agency reserves the right to update or revise these Terms at any time. Material changes will be communicated via our website and, where possible, by direct notification to active Clients. Continued use of our services following any update constitutes acceptance of the revised Terms."
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "The version date and version number displayed at the top of this document indicate the most current revision. Previous versions are archived and available upon written request."
            }
          ]
        }
      ]
    },
    {
      "id": "contact-terms",
      "num": "16",
      "heading": "Contact",
      "blocks": [
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "For all legal enquiries, contract questions, NDA requests, or formal notices under these Terms, please contact:"
            }
          ]
        },
        {
          "type": "contactCard",
          "rows": [
            {
              "icon": "🏢",
              "nodes": [
                {
                  "t": "b",
                  "text": "NexKeys Agency"
                },
                {
                  "t": "br"
                },
                {
                  "t": "s",
                  "text": "Lagos, Nigeria"
                }
              ]
            },
            {
              "icon": "✉",
              "nodes": [
                {
                  "t": "s",
                  "text": "Email:"
                },
                {
                  "t": "a",
                  "text": "nexkeysagency@gmail.com",
                  "href": "mailto:nexkeysagency@gmail.com"
                }
              ]
            },
            {
              "icon": "📞",
              "nodes": [
                {
                  "t": "s",
                  "text": "Phone:"
                },
                {
                  "t": "a",
                  "text": "+234 803 300 4474",
                  "href": "tel:+2348033004474"
                }
              ]
            },
            {
              "icon": "🌐",
              "nodes": [
                {
                  "t": "s",
                  "text": "Response time: Within 48 business hours"
                }
              ]
            }
          ]
        },
        {
          "type": "p",
          "nodes": [
            {
              "t": "s",
              "text": "All formal legal notices must be submitted in writing via email with the subject lineLEGAL NOTICE — [Your Name / Company]."
            }
          ]
        }
      ]
    }
  ]
};
